[1.19] Add support for passing certain methods thru to the Agglomerated Trinkets
glisco03/things pull request #46
Opened 2022-09-13 20:04 UTC by Dragon-Seeker

PR Contains ways of using scrolling to select a given trinket and then passing thru certain methods to certain trinket.

Was designed to fix issue with Artifacts that can be disabled never being able to be re-enabled causing it to be useless

2022-10-22 19:29 UTC, Dragon-Seeker commented
?

2022-10-24 19:51 UTC, gliscowo commented on src/main/java/com/glisco/things/client/ThingsClient.java
> +                var slot = ((HandledScreenAccessor) screen1).thing$getSlotAt(mouseX, mouseY);
`thing` moment

2022-10-24 19:57 UTC, gliscowo requested changes

2022-10-24 19:57 UTC, gliscowo commented on src/main/java/com/glisco/things/items/trinkets/AgglomerationItem.java
> +    public boolean onClicked(ItemStack stack, ItemStack otherStack, Slot slot, ClickType clickType, PlayerEntity player, StackReference cursorStackReference) {
Generally this implementation is fine, not a large fan of `stack1` though - giving it a more descriptive name like `innerStack` or something similar is preferrable

2022-10-24 19:57 UTC, gliscowo commented on src/main/java/com/glisco/things/items/trinkets/AgglomerationItem.java
> +    public <T> T getStackAndRun(ItemStack stack, PlayerEntity player, Function<ItemStack, T> methodPassthru){
`"SelectedTrinket"` should really be an NbtKey

2022-10-24 22:17 UTC, Dragon-Seeker commented on src/main/java/com/glisco/things/client/ThingsClient.java
> +                var slot = ((HandledScreenAccessor) screen1).thing$getSlotAt(mouseX, mouseY);
yep

2022-10-24 22:58 UTC, merged