Added slightly better Simpl. Chinese Translation (take 2)
glisco03/things pull request #8
Opened 2021-08-09 05:23 UTC by LeoCTH

(cc @Neubulae again)

2021-08-09 06:14 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/wax_gland.json
> +      "text": "As great as theses powers are, heat is their downfall. This could be remedied however, if you were to to wear the gland in conjunction with a $(l:things:trinkets/hades_crystal)Hades Cr
Theses?

2021-08-09 09:22 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/recall_potion.json
> +      "text": "历史可能和我的世界本身一样悠久的$(item)回忆药水$()可以通过利用一些尚不明确的在子空间内的奇异变换，将使用者瞬间传送回其$(thing)出生点$()。要想合成这般神药，只需要在$(thing)炼药台$()内将一颗$(item)末影珍珠$()的精华注入到一瓶$(item)粗制的药水$()里即可。"
Why 我的世界 :irriryritritr:
“回忆药水”的历史可能已有Minecraft本体一样悠久。这个药水利用了一点神必的亚空间变换以将使用者传送回出生点。……

2021-08-09 09:32 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/infernal_scepter.json
> +      "text": "$(thing)工欲善其事，必先利其器。$()把$(item)一大桶岩浆$()浇在仅靠一些$(item)下界合金锭$()固定的$(item)烈焰棒$()上听上去不错吧？当然啦！这把$(item)烈焰魔杖$()能够以加热$(item)火焰弹$()的方式将它们发射出去，大幅提高了它们的杀伤力。不过这个过程损耗非常大，就连那刚硬的下界合金也无法一直保持。"
…浇在仅靠~~一些~~下界合金锭………听着不错吧？…………损耗极大，就连刚硬的下界合金也无法保持坚挺。

2021-08-09 09:41 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/gleaming_materials.json
> +      "text": "从$(item)璀璨矿$()中开采出的$(item)璀璨粉$()拥有一些十分有用的魔力，以至于一些魔怔的人甚至认为其必为生命最基本的形态。虽然它本身毫无用处，但它在合成一系列工具与饰品中起到了关键作用。"
…璀璨粉魔力十足，以至于一些魔怔人……起到关键作用

2021-08-09 09:45 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/bater_wucket.json
> +      "text": "传说有云，曾有个名叫贴吧的上古部族，族内奇人层出不穷。一日一位族民锻造了一样名为$(item)『木涌』$()的神器，其内为桶，外漫水，即$(item)『水桶』$()之逆，故称$(item)『木涌』$()。族民惊骇不已，传为佳话。"
古籍暨纪族曰「贴吧」者，间奇人云集。年月日，某覆水于内，盖木其外，得一神器，名之「木涌」，取「水桶」之逆也。众无不惊骇。

2021-08-09 09:45 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/bater_wucket.json
> +      "text": "这玩还是用天知道谁聚合在一块的水做的，居然还能把组成自身的物质几乎无限地倾倒出来……$(p)$(o)$(#999999)……什么鬼啊？？？？？"
这玩意儿就是纯水，至于怎么聚在一起的你问我我问谁？作用：近乎无限地倾倒其组分……什么贵物

2021-08-09 09:46 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/apples.json
> +      "text": "苹果是一种玩家能够食用的食物。$(p)按下并按住使用键来食用快捷栏中的苹果或将它放在脸上（？）。每吃一个苹果增加4点饥饿值与2.4点饱和度。$(p)将一个苹果放入堆肥桶中有65%（13/20）的几率能将堆肥等级提升一级。"
几率~~能~~……

2021-08-09 09:47 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/blocks/glowstone_fixtures.json
> +      "text": "装在一块板子上的一小块萤石。照明时与萤石一样明亮，还会发出一些别致的小粒子。$(p)还挺不戳的，对伐？$()"
OH GOD YOU MADE A BAD
IT'S 荧！！！！！！！！
~~小~~粒子

2021-08-09 09:48 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/blocks/diamond_pressure_plate.json
> +      "text": "虽然一个由$(item)钻石$()做成的压力板可不多见，但它的用途却能使它大放光芒。照这样合成后，这个压力板便$(thing)只会对玩家作出反应$()，十分适合安置在你家门前。"
虽然由钻石……但它的用途使它大放异彩。……十分适合放在你家门口

2021-08-09 09:50 UTC, Neubulae commented on src/main/resources/assets/things/lang/zh_cn.json
> +  "advancement.things.rabbit_foot_charm.title": "B-hop它不香么",
兔子跳

2021-08-09 09:51 UTC, Neubulae requested changes
mostly good, tho imma bikeshedderia

2021-08-09 10:41 UTC, LeoCTH commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/wax_gland.json
> +      "text": "As great as theses powers are, heat is their downfall. This could be remedied however, if you were to to wear the gland in conjunction with a $(l:things:trinkets/hades_crystal)Hades Cr
issue in original text /shrug

2021-08-09 10:47 UTC, LeoCTH commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/hardening_catalyst.json
> +      "text": "将一颗$(item)下界之星$()与许多硬物相结合的产物居然是种液体（？！）不过这种液体有个特殊的属性——在$(thing)铁砧$()上将它倾倒在一个有耐久度的物品上，只要花费一点经验就可以使那个物品变得$(thing)不可破坏$()。"
原文是下界之星（汗

2021-08-09 10:48 UTC, LeoCTH commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/bater_wucket.json
> +      "text": "传说有云，曾有个名叫贴吧的上古部族，族内奇人层出不穷。一日一位族民锻造了一样名为$(item)『木涌』$()的神器，其内为桶，外漫水，即$(item)『水桶』$()之逆，故称$(item)『木涌』$()。族民惊骇不已，传为佳话。"
nb

2021-08-09 10:49 UTC, LeoCTH commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/blocks/glowstone_fixtures.json
> +      "text": "装在一块板子上的一小块萤石。照明时与萤石一样明亮，还会发出一些别致的小粒子。$(p)还挺不戳的，对伐？$()"
>IT'S 荧！！！！！！！！
thonk

2021-08-09 10:51 UTC, LeoCTH commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/blocks/glowstone_fixtures.json
> +      "text": "装在一块板子上的一小块萤石。照明时与萤石一样明亮，还会发出一些别致的小粒子。$(p)还挺不戳的，对伐？$()"
https://minecraft.fandom.com/zh/wiki/%E8%8D%A7%E7%9F%B3
oh fuck you're right
crob

2021-08-09 10:53 UTC, LeoCTH commented on src/main/resources/assets/things/lang/zh_cn.json
> +  "advancement.things.rabbit_foot_charm.title": "B-hop它不香么",
原文是b-hop 我觉得既然b-hop已经成专有名词了也不是不可（（

2021-08-09 12:33 UTC, Neubulae commented on src/main/resources/assets/things/lang/zh_cn.json
> +  "advancement.things.rabbit_foot_charm.title": "B-hop它不香么",
> 原文是b-hop 我觉得既然b-hop已经成专有名词了也不是不可（（

但其实国内叫兔子跳或者直接叫KZ的不少（

2021-08-09 12:35 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/infernal_scepter.json
> +      "text": "$(thing)工欲善其事，必先利其器。$()把$(item)一大桶岩浆$()浇在仅靠$(item)下界合金锭$()固定的$(item)烈焰棒$()上听上去不错吧？这把$(item)烈焰魔杖$()能够以加热$(item)火焰弹$()的方式将它们发射出去，大幅提高了它们的杀伤力。不过这个过程损耗极大，就连刚硬的下界合金法保持坚挺。"
都无法保持坚挺 ohno why typo

2021-08-09 12:38 UTC, Neubulae approved these changes
ready to go I'd assume other than some coce

2021-08-11 04:23 UTC, LeoCTH commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/items/infernal_scepter.json
> +      "text": "$(thing)工欲善其事，必先利其器。$()把$(item)一大桶岩浆$()浇在仅靠$(item)下界合金锭$()固定的$(item)烈焰棒$()上听上去不错吧？这把$(item)烈焰魔杖$()能够以加热$(item)火焰弹$()的方式将它们发射出去，大幅提高了它们的杀伤力。不过这个过程损耗极大，就连刚硬的下界合金法保持坚挺。"
ohno

2021-08-11 04:24 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/ender_pouch.json
> +      "text": "在探索的时候，相信大家都体会过背包满了之后不得不打道回府的痛苦。虽然这个问题不能用普通的材料与手段就能彻底解决，不过我们的$(item)末影袋$()至少能够将探索的时间翻倍——作为一个基本上就是便携末影箱的玩意，它能提供一个与你的$(thing)末影箱内的物品$()的快捷接口。"
……不能用普通的材料和手段彻底解决……提供一个访问末影箱的快捷方式。

2021-08-11 04:25 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/luck_of_the_irish.json
> +      "text": "对一般的Minecraft玩家来说，$(item)毒马铃薯$()像是个没有卵用的累赘。但如果你用它们合成出一个$(item)爱尔兰人的幸运符$()，就能使用它们腐烂的躯骸中提取出无从想象的力量。护符中镶嵌的$(item)璀璨合金$()在学习完其中$(item)附魔金苹果$()的功效之后，可以将佩戴者的一切中毒效果转作$(thing)生命恢复 II$()的效果。"
附魔金苹果其中的功效

2021-08-11 04:26 UTC, LeoCTH commented on src/main/resources/assets/things/lang/zh_cn.json
> +  "advancement.things.rabbit_foot_charm.title": "B-hop它不香么",
tonk

2021-08-11 04:26 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/mining_glove.json
> +      "text": "虽然挖矿是Minecraft的核心游戏机制之一，想要大量地开采还是一个十分艰巨的任务，有一副$(item)挖矿手套$()的话就会简单很多——通过将使用者的双手变得更加强壮、迅捷，使他的挖掘速度大幅提升。"
使用者的双手将变得……

2021-08-11 04:26 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/monocle.json
> +      "text": "单片眼镜早已经被人们用于增强视力。取一片，再在其镜片上撒上一些$(item)璀璨粉$()，就能赋予它一种神秘的光芒；佩戴它时能在已有的功效上，还给予佩戴者$(thing)夜视$()效果。"
能在已有的功效上再赋予佩带者……

2021-08-11 04:29 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/riot_gauntlet.json
> +      "text": "通过结合$(item)璀璨合金$()的魔法属性与两块$(item)下界合金锭$()“映入眼帘”的绝对钝力诞生的$(item)狂暴臂铠$()大幅增强佩戴者的力量。佩带它甚至能让你将一个僵尸徒手撕成两半，是狂战士的好拍档。"
把璀璨合金的魔法，和两块下界合金的绝对武力糊在一起，诞生的狂暴臂铠将大幅增强……

2021-08-11 04:47 UTC, LeoCTH commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/ender_pouch.json
> +      "text": "在探索的时候，相信大家都体会过背包满了之后不得不打道回府的痛苦。虽然这个问题不能用普通的材料与手段就能彻底解决，不过我们的$(item)末影袋$()至少能够将探索的时间翻倍——作为一个基本上就是便携末影箱的玩意，它能提供一个与你的$(thing)末影箱内的物品$()的快捷接口。"
嗯 原文Ender Inventory估计是没想到玩家平常和它唯一的接触方法就是末影箱

2021-08-11 06:29 UTC, Neubulae commented on src/main/resources/data/things/patchouli_books/things_guide/zh_cn/entries/trinkets/mining_glove.json
>      },
ohno remove 通过 so things sound nicer

2021-08-11 07:00 UTC, Neubulae approved these changes

2021-08-11 14:08 UTC, merged